### ISSUE TITLE
.NET Core 3.1 SDK　什么时候出来呢～(When will the .NET Core 3.1 SDK come out?)

### ISSUE THREAD

**Issue by whuanle** [gsvm/loongson-dotnet#2]
.NET Core 3.1 SDK　什么时候出来呢～
Blazor　要 3.1　版本才能运行，但是现在　最新版本是 3.0.1　～

**Comment by xiangzhai** [comment]
git@github.com:aspnet/samples.git

```
commit 91651e59c69749baab6d26f3edcc1798420b37d4
Author: Steve Sanderson <SteveSandersonMS@users.noreply.github.com>
Date:   Fri Sep 20 10:18:33 2019 +0100

    Update FlightFinder to 3.0.0 RC1

```

**Comment by theaoqi** [comment]
还没有明确的时间计划，但是不会太久，可能几个月的时间吧。正式的GA版本应该是3.1。
Blazor无法使用3.0吗？我看3.0也是[支持Blazor](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-3.0)的啊

**Comment by theaoqi** [comment]
[3.1.7](https://github.com/gsvm/loongson-dotnet/releases/tag/ea-20200819) was released.

**Comment by Dapeng-W** [comment]
@theaoqi，啥时候往出放rpm包和srpm包呢？
看http://ftp.loongnix.org/os/loongnix-server/1.7/dotnet/mips64el/Packages/ 和 http://ftp.loongnix.org/os/loongnix-server/1.7/dotnet/Source/SPackages/ 里都是空的呀？

**Comment by theaoqi** [comment]
> @theaoqi，啥时候往出放rpm包和srpm包呢？
> 看http://ftp.loongnix.org/os/loongnix-server/1.7/dotnet/mips64el/Packages/ 和 http://ftp.loongnix.org/os/loongnix-server/1.7/dotnet/Source/SPackages/ 里都是空的呀？

正在跟进，需要些时间，应该不会太久。
