### ISSUE TITLE
[Question] is there docker image for released dotnet runtime 

### ISSUE THREAD

**Issue by leoninew** [gsvm/loongson-dotnet#3]
Hi I've test our apps via released dotnet sdk and runtime, and planing to build docker image for further test. is there any image already or some Dockerfile, which saves our time and made the process move on.

**Comment by xiangzhai** [comment]
Hi @leoninew 

> is there any image already or some Dockerfile

\cc @theaoqi 

Thanks,
Leslie Zhai

**Comment by leoninew** [comment]
Well the result is not good, wait for a while.

**Comment by leoninew** [comment]
Solved after few attempts

```bash
$ cat Dockerfile
FROM debian
WORKDIR /app
COPY aspnetcore-runtime /usr/share/aspnetcore-runtime
RUN ln -s /usr/share/aspnetcore-runtime/dotnet /usr/bin/dotnet

$ docker run --rm -it leoninewang/aspnet:3.0.1 dotnet --list-runtimes
Microsoft.AspNetCore.App 3.0.1 [/usr/share/aspnetcore-runtime/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.0.1 [/usr/share/aspnetcore-runtime/shared/Microsoft.NETCore.App]
```

**Comment by leoninew** [comment]
But push failed with `too many levels of symbolic links`

**Comment by theaoqi** [comment]
Sadly, we don't release docker images at this stage. Maybe we will consider it in further.

Will [dotnet/dotnet-docker](https://github.com/dotnet/dotnet-docker) help to solve your issue? For example: https://github.com/dotnet/dotnet-docker/blob/master/src/aspnet/3.1/bionic/amd64/Dockerfile

**Comment by theaoqi** [comment]
> But push failed with `too many levels of symbolic links`

Just curious, any specific failure information?

**Comment by leoninew** [comment]
Well strange things happened

![image](https://user-images.githubusercontent.com/56761995/90135886-efc18180-dda5-11ea-821d-d173e978b5d5.png)

**Comment by leoninew** [comment]
The screenshot shows error several times, the one caused by ‘dotnet —list-runtimes’ should be noticed, for same command below succeeded. Anything I missed?

**Comment by theaoqi** [comment]
I cannot reproduce the problem.

```
$ docker push aoqi/tmp:tmp
The push refers to repository [docker.io/aoqi/tmp]
f1ad6511af71: Pushed 
5f8c79fc5232: Pushed 
04d335d3c801: Pushed 
1cd4c471abeb: Pushed 
tmp: digest: sha256:c8390020f5cd82e4bfc6e582f91fa592ac915c470c346d65fc41c73c06257e92 size: 1154

$ for((i=0;i<=100;i++)); do docker run  --rm aoqi/tmp:tmp dotnet --list-runtimes | grep -v 3.0.1; done
```
The above commands just work fine.


My docker version:
```
$ docker version
Client:
 Version:           18.06.3.ce
 API version:       1.38
 Go version:        go1.11.5
 Git commit:        d7080c17a580919f5340a15a8e5e013133089680
 Built:             Mon Sep  2 06:20:00 2019
 OS/Arch:           linux/mips64le
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3.ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.11.5
  Git commit:       d7080c17a580919f5340a15a8e5e013133089680
  Built:            Mon Sep  2 06:24:01 2019
  OS/Arch:          linux/mips64le
  Experimental:     false

```

**Comment by geffzhang** [comment]
Very much need docker, containerization is the advantage of .net, the use of resources less, the start speed. We are very much looking forward to providing docker images as soon as possible.
@theaoqi Release version 3.1, 7 as soon as possible, and perhaps the above problem disappears.

**Comment by xied75** [comment]
I had a google search on term "docker too many levels of symbolic links", looks like there are lots of reports on various projects, so very likely to be docker engine's problem. Shouldn't be anything to do with our work here.

**Comment by leoninew** [comment]
closed due to the new release published.
