### ISSUE TITLE
编译项目出错过程(Failed to compiling a project )

### ISSUE THREAD

**Issue by whuanle** [gsvm/loongson-dotnet#5]
环境：
![image](https://user-images.githubusercontent.com/2189761/91451395-f379fb80-e8af-11ea-9ccf-7863a1581b9e.png)
测试项目：
https://github.com/dotnetcore/Natasha

clone 项目后，打开解决方案的 `test/NatashaUT` 目录，执行：
```
dotnet test
```
出现大量错误：
![image](https://user-images.githubusercontent.com/2189761/91451857-769b5180-e8b0-11ea-8df8-94843ef42d4b.png)

以上是 NCC 开源组织的 Natasha 项目。
我正在开发的一个基于 Roslyn 的项目（暂时没完成，没开源），执行示例程序时，出现：
```
A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/var/Natasha/CZGL.CodeAnalysis/xamples/ConsoleTest/bin/Debug/netcoreapp3.1/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].

```

**Comment by xiangzhai** [comment]
Hi @whuanle 

Thanks for your bug report!

> ![image](https://user-images.githubusercontent.com/2189761/91451857-769b5180-e8b0-11ea-8df8-94843ef42d4b.png)

The latest SDK fixed the issue.  Please test again for the next EA release.

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
@whuanle  PING
